# Site settings
title: Zank's Blog
email: yww7289@163.com
description: "being full-stack"
permalink: '/:categories/:title'

# Build settings
# permalink: date

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]

#duoshuo
  comments :
    provider : duoshuo
    duoshuo :
      short_name : taizilongxu

navigations:
  - title: Archive
    class: fa fa-tags
    href: /archive/
  - title: Categories
    class: fa fa-user
    href: /categories/
  - title : Tags
    class: fa fa-tags
    href: /tags/